# This is a basic workflow to help you get started with Actions

name: CI/CD for function.php deployment to PELERINAGES-LYON

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Configuration for main branch
      if: ${{ GITHUB.REF == 'refs/heads/main' }}
      run: |
        echo "FTP_USERNAME=${{ secrets.PROD_FTP_USERNAME }}" >> $GITHUB_ENV
        echo "FTP_PWD=${{ secrets.PROD_FTP_PWD }}" >> $GITHUB_ENV

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: FTP Deploy to hosting
      if:  env.FTP_USERNAME != null && env.FTP_PWD != null
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        # ftp server
        server: ${{ secrets.FTP_SERVER }}
        # ftp username
        username: ${{ env.FTP_USERNAME }}
        # ftp password
        password: ${{ env.FTP_PWD }}
        # server directory to push files
        server-dir: ${{ secrets.FTP_SERVER_DIR }}
        # local dir to upload
        local-dir: ./blocksy-child/
        # An array of glob patterns, these files will not be included in the publish/delete process
        exclude: |
          **/.git*
          **/.git*/**
          README.md
